apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mysql

resources:
  - ../../../../platform/cluster/mysql-adminer

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: mysql-adminer.development.wapps.com
    target:
      kind: Ingress
      name: mysql-adminer-ingress

