apiVersion: v1
kind: ConfigMap
metadata:
  name: discussion-materializer-config
  namespace: discussion
data:
  # RabbitMQ
  QUEUE_HOST: rabbitmq.rabbitmq
  QUEUE_PORT: "5672"

  # MinIO (S3 compatible)
  DISCUSSION_STORAGE_HOST: http://minio.minio:9000

  # MongoDB (materialized projections)
  MONGO_HOST: mongodb.mongodb
  MONGO_PORT: "27017"
  MONGO_DATABASE: wapps

