apiVersion: v1
kind: Service
metadata:
  name: platform-portal-csr-service
  labels:
    app: platform-portal-csr
    app.kubernetes.io/name: platform-portal-csr
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: platform-portal-csr
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

