apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discussion

resources:
  - ../../../../apps/services/discussion-materializer/provisioning/k8s

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: discussion-materializer

