apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rabbitmq

resources:
  - ../../../../platform/cluster/rabbitmq/ingress.yaml

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: rabbitmq.development.wapps.com
    target:
      kind: Ingress
      name: rabbitmq-ingress

# Note: Namespace and Helm resources managed by rabbitmq ArgoCD app
# This overlay only manages environment-specific ingress configuration

