apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: catalog-bff-ingress
  namespace: catalog
  labels:
    app: catalog-bff
    app.kubernetes.io/name: catalog-bff
    app.kubernetes.io/component: bff
    app.kubernetes.io/part-of: catalog
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: api.wapps.local
      http:
        paths:
          - path: /catalog(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: catalog-bff-service
                port:
                  number: 80

