apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: catalog

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd

images:
  - name: ghcr.io/gitarzysta92/catalog-bff
    newTag: latest

