apiVersion: v1
kind: Service
metadata:
  name: catalog-bff-service
  namespace: catalog
  labels:
    app: catalog-bff
    app.kubernetes.io/name: catalog-bff
    app.kubernetes.io/component: bff
    app.kubernetes.io/part-of: catalog
spec:
  type: ClusterIP
  selector:
    app: catalog-bff
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

