apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aggregator-ssr-ingress
  namespace: aggregator
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: aggregator-ssr.development.wapps.ai
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aggregator-ssr-service
            port:
              number: 80

