apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aggregator

resources:
  - ../../../../apps/portals/aggregator/entrypoints/ssr/provisioning/k8s

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

