apiVersion: v1
kind: Service
metadata:
  name: account-management
  namespace: default
  labels:
    app: account-management
    app.kubernetes.io/name: account-management
    app.kubernetes.io/component: identity-admin
    app.kubernetes.io/part-of: platform
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 1340
      protocol: TCP
      name: http
  selector:
    app: account-management

