apiVersion: v1
kind: Service
metadata:
  name: authenticator
  namespace: default
  labels:
    app: authenticator
    app.kubernetes.io/name: authenticator
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: platform
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: authenticator

