apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: editorial-ingress
  namespace: editorial
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"  # Optional, for HTTP setups
spec:
  rules:
    - host: editorial-service.wapps.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: editorial
                port:
                  number: 1337