apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: editorial

resources:
  - editorial.deployment.yaml
  - editorial.service.yaml
  - editorial.service-account.yaml
  - editorial.ingress.yaml

