apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    description: "RabbitMQ configuration overlay (ingress)"
spec:
  project: wapps-platform
  source:
    repoURL: https://github.com/Gitarzysta92/wapps.git
    targetRevision: HEAD
    path: environments/dev/platform/rabbitmq-kustomization
  destination:
    server: https://kubernetes.default.svc
    namespace: rabbitmq
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false  # Namespace created by Helm chart
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

