apiVersion: v1
kind: ConfigMap
metadata:
  name: media-ingestion-config
  labels:
    app: media-ingestion
    app.kubernetes.io/name: media-ingestion
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: services
data:
  MEDIA_STORAGE_HOST: "http://minio.minio:9000"
  QUEUE_HOST: "rabbitmq.rabbitmq"
  QUEUE_PORT: "5672"
