apiVersion: v1
kind: ServiceAccount
metadata:
  name: media-ingestion
  labels:
    app: media-ingestion
    app.kubernetes.io/name: media-ingestion
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: services
