apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: editorial

resources:
  - editor-agent.deployment.yaml
  - editor-agent.service-account.yaml
  - editor-agent.config-map.yaml

