apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: catalog

resources:
  - ../../../../apps/services/catalog-bff/provisioning/k8s

patchesStrategicMerge:
  - deployment-patch.yaml

images:
  - name: ghcr.io/gitarzysta92/catalog-bff
    newTag: latest

