apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: content-node-registry-ingress
  namespace: content-node-registry
  labels:
    app: content-node-registry
    app.kubernetes.io/name: content-node-registry
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: content
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /api/$2
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: api.wapps.local
      http:
        paths:
          - path: /content-node-registry(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: content-node-registry-service
                port:
                  number: 80
