apiVersion: v1
kind: Service
metadata:
  name: content-node-registry-service
  namespace: content-node-registry
  labels:
    app: content-node-registry
    app.kubernetes.io/name: content-node-registry
    app.kubernetes.io/component: service
    app.kubernetes.io/part-of: content
spec:
  type: ClusterIP
  selector:
    app: content-node-registry
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
