apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-portal-bff
  labels:
    app: platform-portal-bff
    app.kubernetes.io/name: platform-portal-bff
    app.kubernetes.io/component: backend

