apiVersion: v1
kind: Service
metadata:
  name: platform-portal-bff-service
  labels:
    app: platform-portal-bff
    app.kubernetes.io/name: platform-portal-bff
    app.kubernetes.io/component: backend
spec:
  selector:
    app: platform-portal-bff
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

