apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mongodb

resources:
  - ../../../../platform/cluster/mongo-express

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: mongo-express.development.wapps.com
    target:
      kind: Ingress
      name: mongo-express-ingress

