apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingress.yaml
  - argocd-cm.yaml
  - argocd-rbac-cm.yaml

# Note: The actual ArgoCD installation will be done via:
# kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
# These ConfigMaps should be applied after ArgoCD installation, or they can be created beforehand.
