apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: editorial

resources:
  - ../../../../apps/agents/editor/provisioning/k8s

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: editor-agent

