apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: editorial

resources:
  - ../../../../apps/agents/editor/provisioning/k8s/editor-agent.namespace.yaml
  - ../../../../apps/agents/editor/provisioning/k8s/editor-agent.service-account.yaml
  - ../../../../apps/agents/editor/provisioning/k8s/editor-agent.config-map.yaml
  - ../../../../apps/agents/editor/provisioning/k8s/editor-agent.deployment.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: editor-agent

