apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: account-management-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    # Recommended: restrict this ingress in env overlays
    # nginx.ingress.kubernetes.io/whitelist-source-range: "10.0.0.0/8"
spec:
  rules:
    - host: account-management.development.wapps.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: account-management
                port:
                  number: 80

