apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../../../apps/services/account-management/provisioning/k8s

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: account-management
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: account-management-ingress

