apiVersion: v1
kind: Service
metadata:
  name: mysql-adminer
  namespace: mysql
  labels:
    app: mysql-adminer
    app.kubernetes.io/name: mysql-adminer
    app.kubernetes.io/part-of: platform
spec:
  type: ClusterIP
  selector:
    app: mysql-adminer
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

