apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: opa

resources:
  - namespace.yaml
  - service.yaml
  - deployment.yaml

configMapGenerator:
  - name: opa-bundle-discussion
    files:
      - bundles/discussion/data.json
      - bundles/discussion/policy.rego

generatorOptions:
  disableNameSuffixHash: true

