apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agents

resources:
  - discord-notifier.deployment.yaml
  - discord-notifier.service-account.yaml
  - discord-notifier.config-map.yaml
  - discord-notifier.pvc.yaml
