apiVersion: v1
kind: Service
metadata:
  name: discussion-csr-service
  namespace: aggregator
  labels:
    app: discussion-csr
    app.kubernetes.io/name: discussion-csr
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: discussion-csr
  ports:
    - name: http
      port: 80
      targetPort: 80
  type: ClusterIP

