apiVersion: apps/v1
kind: Deployment
metadata:
  name: editorial
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: editorial
        image: editorial:dev-latest
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: "development"
        - name: HOST
          value: "0.0.0.0"
        - name: PORT
          value: "1337"
        # Database credentials from Kubernetes secret (created by Ansible)
        - name: DATABASE_CLIENT
          valueFrom:
            secretKeyRef:
              name: editorial-db-credentials
              key: DATABASE_CLIENT
        - name: DATABASE_HOST
          valueFrom:
            secretKeyRef:
              name: editorial-db-credentials
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            secretKeyRef:
              name: editorial-db-credentials
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            secretKeyRef:
              name: editorial-db-credentials
              key: DATABASE_NAME
        - name: DATABASE_USERNAME
          valueFrom:
            secretKeyRef:
              name: editorial-db-credentials
              key: DATABASE_USERNAME
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: editorial-db-credentials
              key: DATABASE_PASSWORD
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 512Mi

