apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: editorial

resources:
  - ../../../../apps/services/editorial/provisioning/k8s

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: editorial
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: editorial-ingress
