apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: editorial

resources:
  - ../../../../apps/services/editorial/provisioning/k8s

patchesStrategicMerge:
  - deployment-patch.yaml
  - ingress-patch.yaml

