apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/scrappers/store-app/provisioning/k8s
patches:
  - path: cronjob-patch.yaml
    target:
      kind: CronJob
      name: store-app-scrapper

