apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discussion

resources:
  - discussion-materializer.configmap.yaml
  - discussion-materializer.service-account.yaml
  - discussion-materializer.deployment.yaml

