apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: aggregator

resources:
  - ../../../../apps/portals/catalog/entrypoints/csr/provisioning/k8s

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: catalog-csr
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: catalog-csr-ingress
