apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acquisition

resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - cronjob.yaml
  # Note: job.yaml is for manual execution, not managed by ArgoCD

commonLabels:
  app.kubernetes.io/managed-by: argocd

