apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aggregator-csr-ingress
  namespace: aggregator
  labels:
    app: aggregator-csr
    app.kubernetes.io/name: aggregator-csr
    app.kubernetes.io/component: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: aggregator-csr.wapps.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aggregator-csr-service
            port:
              number: 80
