apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-portal-csr-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: platform-portal-csr.development.wapps.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: platform-portal-csr-service
            port:
              number: 80
  - host: platform.development.wapps.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: platform-portal-csr-service
            port:
              number: 80

