apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: discussion

resources:
  - discussion.namespace.yaml
  - discussion.configmap.yaml
  - discussion.deployment.yaml
  - discussion.service.yaml
  - discussion.service-account.yaml
  - discussion.ingress.yaml
