apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../apps/services/media-ingestion/provisioning/k8s
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: media-ingestion
