apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - deployment.yaml

commonLabels:
  app.kubernetes.io/managed-by: argocd

images:
  - name: firebase-auth-validator
    newName: ghcr.io/gitarzysta92/wapps/firebase-auth-validator
    newTag: latest

